import './styles/main.css'
import './styles/utilitys.css'

import './modules/card/card.js'
import './modules/form/submit.js'
import './modules/card/music.js'
import './modules/card/timer.js'
import './modules/events.js'
import './modules/page-load.js'
import './modules/tasks/cancel.js'
